### ISSUE TITLE
About maskrcnn-benchmark scripting problem

### ISSUE THREAD

**Issue by ys0823** [kdethoor/dotfiles#1]
I feel sorry to ask questions here, I couldn't find your public email, so I ask the question here.
I saw your discussion in [https://github.com/facebookresearch/maskrcnn-benchmark/pull/138](url), I do the same problem with you,and i want to get a `custom ops.dll` in `windows 10`,and i can also use the `cmakeLists` to get a `custom ops.dll` for`gpu`, but I have some problems when compiling by pytorch cuda,I don't know whether you try it to get a `gpu` `custom ops.dll` or not,can you give me some suggestions?
`Hi,
First of all, thank you for this great work !

I've successfully managed to install maskrcnn-benchmark and run the webcam demo in Python. I'm highly interested in converting the maskrcnn models into TorchScript modules, but unfortunately it doesn't work properly for me. More precisely, I have applied the patch proposed here (I tried both on the latest commit and on the commit it was originally applied in Nov 2018), I get the end_to_end_model.pt, I can run it on the image I used to trace the model, but the TorchScript module crashes when I try to run on another image of the same dimension (640x480). I'll put the error message below as well as some of my config details (I tried to look at the forward functions mentioned here below, but in vain...). Any idea of what it could be ?

Thanks again for this wonderful repo.

Config notes:

Windows 10 x64
Conda
Python 3.7
pytorch(1.0.0, py3.7_cuda90_cudnn7_1, pytorch) <- repo is working without the nightly version according to what I read here
pytorch-cpu (1.0.0, py3.7_cpu_1, pytorch) <- only using the CPU, for inference
Installed maskrcnn-benchmark with the original setup.py (built with vc 15 ver 14.16) and built the custom ops manually using CMake
py-opencv (3.4.2, py37hc319ecb_0)
libopencv (3.4.2, h20b85fd_0)`

**Comment by kdethoor** [comment]
Hi Yesheng,

For what I was working on, I only tried with the CPU. Moreover, if I
remember well, I couldn't get past that point with that repo and being limited by time, so I ended up
following another road. So, unfortunately I won't be able to help you with that, I'm
sorry.

Hoping you'll find or you've found a solution and wishing you a great day.

Sincerely,
Kevin
